version: '3.9'

services:
  github:
    build:
      context: src/node
      dockerfile: Dockerfile
      args:
        - NODE_VERSION=20.11.0
    restart: unless-stopped
    container_name: github_runner
    platform: linux/arm64
    tty: true  
    stdin_open: true
    environment:
      REPO_URL: https://github.com/salmonstats3/av5ja_stats_api
      RUNNER_NAME: intel.n100
      RUNNER_SCOPE: repo
      RUN_AS_ROOT: true
      ACCESS_TOKEN: $ACCESS_TOKEN
    security_opt:
      - label:disable
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'